### ISSUE TITLE
error with a simple raster

### ISSUE THREAD

**Issue by ludovico85** [mattmar/spectralrao#5]
Hi, I'm getting the following error:

`raomatrix<-spectralrao(ndvi1,distance_m="euclidean",window=3,shannon=FALSE)
`
```
Converting input data in an integer matrix...
Matrix check OK: 
Rao output matrix will be returned
 Show Traceback
 
 Rerun with Debug
 Error in do.call(".Call", c(list(method), list(x), list(y), pairwise,  : 
  negative length vectors are not allowed
``` 

[ndvi1.zip](https://github.com/mattmar/spectralrao/files/4553680/ndvi1.zip)

**Comment by mattmar** [comment]
Hi Ludovico,

spectralrao is now integrated in the '*rasterdiv' R *package here:
https://cran.r-project.org/web/packages/rasterdiv/index.html and is called
Rao.
after installing and loading the package, run it with:

raomatrix <- Rao(ndvi1,dist_m="euclidean",window=3,shannon=FALSE)
let me know if you have any issues.
Matteo

**Comment by ludovico85** [comment]
I've tried with the rasterdiv package but I've received the same error.

Grazie.

**Comment by mattmar** [comment]
Ciao Ludovico,

The issue is that your image has got many pixels with different values so R is not able to handle the distance matrix (would be approximately 280 Gb!). You have two solutions, "simplify" the problem decreasing the number of decimal places with:

raomatrix <- Rao(ndvi1,dist_m="euclidean",window=3,shannon=FALSE, simplify=2)

This is safe as NDVI information after the second-third decimal is not very informative.

Or work with 8-bit NDVI data (0-255).

Hope this helps,
Matteo

Matteo

**Comment by ludovico85** [comment]
Thank you! Now the algorithm works fine.
