### ISSUE TITLE
cant make the prosess done in linux

### ISSUE THREAD

**Issue by mmadrz** [mattmar/spectralrao#7]
![Screenshot from 2022-11-08 17-37-10](https://user-images.githubusercontent.com/117746151/200585979-e5269315-d7ec-4fcc-9f52-726cfef4fc39.png)
Hi, I'm using your code for an ecological study and the problem is that when the process reaches 100% it still can't be done.
I'm using a virtual ubuntu machine (I'm not so familiar with Linux and I'm using it just for the benefits of parallel calculation) and so I can't update from the terminal by Sudo apt-get update (because of the proxy).
I'm wondering if it's because of updating issue or not. and if you have any idea how to make it right.

**Comment by mattmar** [comment]
Hi mmdarz, 

I do not develop spectralrao since 2017,. Spectralrao function is now integrated in the rasterdiv R package, I suggest you use the functions in this package, check here:

https://github.com/mattmar/rasterdiv

I guess you're especially interested in the paRao() function of this package.

Matteo

**Comment by mmadrz** [comment]
thank you so much, that was so helpful.

**Comment by mattmar** [comment]
Cool!
